version: '3.5'
services:
    webapp:
        container_name: todo_webapp
        build:
            context: .
            target: development
        ports:
            - '4123:80'
        restart: unless-stopped
        volumes:
            - .:/srv/app
        networks:
            - default
        environment:
            HOST: 'mongodb'
            DATABASE: 'todo_data'
            USERNAME: 'mongouser'
            PASSWORD: 'mongopassword'
            PYTHONIOENCODING: 'utf-8'
            TZ: "Asia/Manila"
        # command: ['ping', '127.0.0.1']
    mongodb:
        container_name: todo_mongodb
        image: mongo:4.2.0-bionic
        restart: unless-stopped
        volumes:
            - todo-mongodb-data:/data/db
        networks:
            - default
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongouser
            MONGO_INITDB_ROOT_PASSWORD: mongopassword
            TZ: "Asia/Manila"
        logging:
            driver: "json-file"
            options:
                max-size: "256m"
volumes:
    todo-mongodb-data:
